"""Synthetic data generation utilities."""

from .artifact import (
    SyntheticArtifactOccurrence,
    SyntheticRandomBoxArtifactConfig,
    SyntheticScheduledBoxArtifactConfig,
    SyntheticSessionStartSpikeConfig,
    add_random_box_artifacts,
    add_scheduled_box_artifacts,
    configure_session_start_spike,
)
from .doric import (
    SyntheticDoricConfig,
    SyntheticDoricSummary,
    SyntheticGaussianNoiseConfig,
    SyntheticRandomCalciumEventConfig,
    SyntheticScheduledCalciumEventConfig,
    SyntheticSignalConfig,
    SyntheticTonicComponentConfig,
    SyntheticTTLBehaviorCodeConfig,
    SyntheticTTLBehaviorEventConfig,
    SyntheticTTLBehaviorEventSummary,
    SyntheticTTLRandomBehaviorEventConfig,
    add_gaussian_noise,
    add_random_calcium_events,
    add_scheduled_calcium_events,
    add_tonic_component,
    generate_synthetic_doric,
)

__all__ = [
    "SyntheticArtifactOccurrence",
    "SyntheticDoricConfig",
    "SyntheticDoricSummary",
    "SyntheticGaussianNoiseConfig",
    "SyntheticRandomBoxArtifactConfig",
    "SyntheticRandomCalciumEventConfig",
    "SyntheticScheduledBoxArtifactConfig",
    "SyntheticScheduledCalciumEventConfig",
    "SyntheticSessionStartSpikeConfig",
    "SyntheticSignalConfig",
    "SyntheticTTLBehaviorCodeConfig",
    "SyntheticTTLBehaviorEventConfig",
    "SyntheticTTLBehaviorEventSummary",
    "SyntheticTTLRandomBehaviorEventConfig",
    "SyntheticTonicComponentConfig",
    "add_gaussian_noise",
    "add_random_box_artifacts",
    "add_random_calcium_events",
    "add_scheduled_box_artifacts",
    "add_scheduled_calcium_events",
    "add_tonic_component",
    "configure_session_start_spike",
    "generate_synthetic_doric",
]
