"""Synthetic data generation utilities."""

from .artifact import (
    SyntheticArtifactOccurrence,
    SyntheticPhotometryDisconnectionConfig,
    SyntheticRandomBoxArtifactConfig,
    SyntheticScheduledBoxArtifactConfig,
    SyntheticSessionStartSpikeConfig,
    add_random_box_artifacts,
    add_scheduled_box_artifacts,
    configure_photometry_disconnection,
    configure_session_start_spike,
)
from .doric import (
    SyntheticDoricConfig,
    SyntheticDoricSummary,
    SyntheticGaussianNoiseConfig,
    SyntheticRandomCalciumEventConfig,
    SyntheticScheduledCalciumEventConfig,
    SyntheticSignalConfig,
    SyntheticTonicComponentConfig,
    SyntheticTTLBehaviorCodeConfig,
    SyntheticTTLBehaviorEventConfig,
    SyntheticTTLBehaviorEventSummary,
    SyntheticTTLRandomBehaviorEventConfig,
    add_gaussian_noise,
    add_random_calcium_events,
    add_scheduled_calcium_events,
    add_tonic_component,
    generate_synthetic_doric,
)
from .photobleaching import (
    SyntheticPhotobleachingComponentConfig,
    SyntheticPhotobleachingConfig,
    SyntheticPhotobleachingMetadata,
)
from .tdt import (
    SyntheticTDTBatchSummary,
    SyntheticTDTExtractionRecord,
    SyntheticTDTSubject,
    build_tdt_epocs_from_behavior_events,
    export_synthetic_tdt_extracts,
)

__all__ = [
    "SyntheticArtifactOccurrence",
    "SyntheticDoricConfig",
    "SyntheticDoricSummary",
    "SyntheticGaussianNoiseConfig",
    "SyntheticPhotobleachingComponentConfig",
    "SyntheticPhotobleachingConfig",
    "SyntheticPhotobleachingMetadata",
    "SyntheticPhotometryDisconnectionConfig",
    "SyntheticRandomBoxArtifactConfig",
    "SyntheticRandomCalciumEventConfig",
    "SyntheticScheduledBoxArtifactConfig",
    "SyntheticScheduledCalciumEventConfig",
    "SyntheticSessionStartSpikeConfig",
    "SyntheticSignalConfig",
    "SyntheticTTLBehaviorCodeConfig",
    "SyntheticTTLBehaviorEventConfig",
    "SyntheticTTLBehaviorEventSummary",
    "SyntheticTTLRandomBehaviorEventConfig",
    "SyntheticTDTBatchSummary",
    "SyntheticTDTExtractionRecord",
    "SyntheticTDTSubject",
    "SyntheticTonicComponentConfig",
    "add_gaussian_noise",
    "add_random_box_artifacts",
    "add_random_calcium_events",
    "add_scheduled_box_artifacts",
    "add_scheduled_calcium_events",
    "add_tonic_component",
    "configure_photometry_disconnection",
    "configure_session_start_spike",
    "build_tdt_epocs_from_behavior_events",
    "export_synthetic_tdt_extracts",
    "generate_synthetic_doric",
]
