"""Doric HDF5 loading utilities."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import h5py
import numpy as np

from ..models import DoricDataset

_LOCKIN_RE = re.compile(r"^AIN(?P<channel>\d{2})xAOUT(?P<output>\d{2})-LockIn$")


class DoricFileError(ValueError):
    """Raised when a Doric HDF5 file has an unsupported or malformed layout."""


def load_doric(
    path: str | Path,
    *,
    signal_root: str = "DataAcquisition/FPConsole/Signals",
    isosbestic_output: int = 1,
    calcium_output: int = 2,
) -> DoricDataset:
    """Load Doric FPConsole lock-in traces from an HDF5 ``.doric`` file.

    The returned arrays are normalized to ``(samples, channels, series)`` and
    can be passed directly to ``analyze_sessions``. This loader supports the
    Doric-style HDF5 hierarchy generated by
    ``circadian_fiber_photometry.simulation.generate_synthetic_doric`` and
    raises clear errors for unsupported layouts.
    """

    if isosbestic_output <= 0 or calcium_output <= 0:
        raise ValueError("output numbers must be positive")
    if isosbestic_output == calcium_output:
        raise ValueError("isosbestic_output and calcium_output must differ")

    h5_path = Path(path)
    if not h5_path.exists():
        raise FileNotFoundError(h5_path)

    with h5py.File(h5_path, "r") as h5_file:
        signals = _require_group(h5_file, signal_root)
        series_names = _series_names(signals)
        first_series = _require_group(signals, series_names[0])
        channel_numbers = _lockin_channels_for_outputs(
            first_series,
            isosbestic_output,
            calcium_output,
        )

        timestamps_by_series: list[np.ndarray] = []
        iso_by_series: list[np.ndarray] = []
        calcium_by_series: list[np.ndarray] = []
        samples_per_series: int | None = None

        for series_name in series_names:
            series = _require_group(signals, series_name)
            series_time: np.ndarray | None = None
            iso_channels = []
            calcium_channels = []

            for channel_number in channel_numbers:
                iso_group = _require_lockin_group(
                    series,
                    channel_number,
                    isosbestic_output,
                )
                calcium_group = _require_lockin_group(
                    series,
                    channel_number,
                    calcium_output,
                )
                iso_time = _read_1d_dataset(iso_group, "Time")
                calcium_time = _read_1d_dataset(calcium_group, "Time")
                iso_values = _read_1d_dataset(iso_group, "Values")
                calcium_values = _read_1d_dataset(calcium_group, "Values")

                _require_same_length(
                    iso_time,
                    iso_values,
                    f"{series_name}/{iso_group.name}",
                )
                _require_same_length(
                    calcium_time,
                    calcium_values,
                    f"{series_name}/{calcium_group.name}",
                )
                if iso_time.shape != calcium_time.shape or not np.allclose(
                    iso_time,
                    calcium_time,
                ):
                    raise DoricFileError(
                        f"{series_name} channel AIN{channel_number:02d} lock-in "
                        "time vectors do not match"
                    )

                if series_time is None:
                    series_time = iso_time
                elif series_time.shape != iso_time.shape or not np.allclose(
                    series_time,
                    iso_time,
                ):
                    raise DoricFileError(
                        f"{series_name} lock-in channels do not share one time vector"
                    )

                iso_channels.append(iso_values)
                calcium_channels.append(calcium_values)

            if series_time is None:
                raise DoricFileError(f"{series_name} contains no lock-in time vector")

            if samples_per_series is None:
                samples_per_series = int(series_time.size)
            elif series_time.size != samples_per_series:
                raise DoricFileError(
                    "series have unequal sample counts; normalize or trim the file "
                    "before loading"
                )

            timestamps_by_series.append(series_time)
            iso_by_series.append(np.column_stack(iso_channels))
            calcium_by_series.append(np.column_stack(calcium_channels))

        if samples_per_series is None:
            raise DoricFileError("no series data were loaded")

        timestamps = np.column_stack(timestamps_by_series)
        isosbestic_405 = np.stack(iso_by_series, axis=2)
        calcium_465 = np.stack(calcium_by_series, axis=2)

        return DoricDataset(
            path=h5_path,
            isosbestic_405=isosbestic_405,
            calcium_465=calcium_465,
            timestamps=timestamps,
            fs=_infer_sampling_rate(timestamps),
            series_names=series_names,
            channel_names=tuple(
                f"AIN{channel_number:02d}" for channel_number in channel_numbers
            ),
            analog_in=_read_auxiliary_series(
                signals,
                series_names,
                "AnalogIn",
                samples_per_series,
            ),
            analog_out=_read_auxiliary_series(
                signals,
                series_names,
                "AnalogOut",
                samples_per_series,
            ),
            digital_io=_read_auxiliary_series(
                signals,
                series_names,
                "DigitalIO",
                samples_per_series,
            ),
            metadata=_read_metadata(h5_file, signal_root),
        )


def _require_group(parent: h5py.Group | h5py.File, path: str) -> h5py.Group:
    try:
        node = parent[path]
    except KeyError as exc:
        raise DoricFileError(f"missing required Doric group: {path}") from exc
    if not isinstance(node, h5py.Group):
        raise DoricFileError(f"expected Doric group at {path}")
    return node


def _series_names(signals: h5py.Group) -> tuple[str, ...]:
    names = tuple(
        sorted(
            (
                name
                for name, node in signals.items()
                if name.startswith("Series") and isinstance(node, h5py.Group)
            ),
            key=_series_sort_key,
        )
    )
    if not names:
        raise DoricFileError(f"no Series groups found under {signals.name}")
    return names


def _series_sort_key(name: str) -> tuple[int, int | str]:
    match = re.fullmatch(r"Series(\d+)", name)
    if match is None:
        return (1, name)
    return (0, int(match.group(1)))


def _lockin_channels_for_outputs(
    series: h5py.Group,
    isosbestic_output: int,
    calcium_output: int,
) -> tuple[int, ...]:
    iso_channels = _lockin_channel_numbers(series, isosbestic_output)
    calcium_channels = _lockin_channel_numbers(series, calcium_output)
    channel_numbers = tuple(sorted(iso_channels & calcium_channels))
    if not channel_numbers:
        raise DoricFileError(
            f"{series.name} has no matching AOUT{isosbestic_output:02d} and "
            f"AOUT{calcium_output:02d} lock-in channels"
        )
    return channel_numbers


def _lockin_channel_numbers(series: h5py.Group, output_number: int) -> set[int]:
    numbers = set()
    for name, node in series.items():
        if not isinstance(node, h5py.Group):
            continue
        match = _LOCKIN_RE.fullmatch(name)
        if match is None:
            continue
        if int(match.group("output")) == output_number:
            numbers.add(int(match.group("channel")))
    return numbers


def _require_lockin_group(
    series: h5py.Group,
    channel_number: int,
    output_number: int,
) -> h5py.Group:
    name = f"AIN{channel_number:02d}xAOUT{output_number:02d}-LockIn"
    return _require_group(series, name)


def _read_1d_dataset(group: h5py.Group, name: str) -> np.ndarray:
    if name not in group:
        raise DoricFileError(f"missing dataset: {group.name}/{name}")
    dataset = group[name]
    if not isinstance(dataset, h5py.Dataset):
        raise DoricFileError(f"expected dataset at {group.name}/{name}")
    values = np.asarray(dataset[:], dtype=float)
    if values.ndim != 1:
        raise DoricFileError(f"{group.name}/{name} must be a 1D dataset")
    if values.size == 0:
        raise DoricFileError(f"{group.name}/{name} must not be empty")
    if not np.all(np.isfinite(values)):
        raise DoricFileError(f"{group.name}/{name} contains NaN or infinite values")
    return values


def _require_same_length(
    left: np.ndarray,
    right: np.ndarray,
    label: str,
) -> None:
    if left.size != right.size:
        raise DoricFileError(f"{label} Time and Values datasets differ in length")


def _infer_sampling_rate(timestamps: np.ndarray) -> float:
    if timestamps.shape[0] < 2:
        raise DoricFileError("at least two timestamp samples are required")

    sample_steps = np.diff(timestamps, axis=0)
    if np.any(sample_steps <= 0):
        raise DoricFileError("timestamps must increase within each series")
    fs_values = 1.0 / np.median(sample_steps, axis=0)
    fs = float(np.median(fs_values))
    if not np.allclose(fs_values, fs, rtol=1e-4, atol=1e-8):
        raise DoricFileError(
            f"series sampling rates differ; inferred rates={fs_values.tolist()}"
        )
    return fs


def _read_auxiliary_series(
    signals: h5py.Group,
    series_names: tuple[str, ...],
    group_name: str,
    samples_per_series: int,
) -> dict[str, np.ndarray]:
    presence = [group_name in signals[series_name] for series_name in series_names]
    if not any(presence):
        return {}
    if not all(presence):
        raise DoricFileError(f"{group_name} group is missing from some series")

    first_group = _require_group(_require_group(signals, series_names[0]), group_name)
    channel_names = tuple(
        name
        for name, node in first_group.items()
        if name != "Time" and isinstance(node, h5py.Dataset)
    )
    output: dict[str, np.ndarray] = {}

    for channel_name in channel_names:
        channel_values = []
        for series_name in series_names:
            series_group = _require_group(signals, series_name)
            aux_group = _require_group(series_group, group_name)
            values = _read_1d_dataset(aux_group, channel_name)
            if values.size != samples_per_series:
                raise DoricFileError(
                    f"{series_name}/{group_name}/{channel_name} has "
                    f"{values.size} samples; expected {samples_per_series}"
                )
            channel_values.append(values)
        output[channel_name] = np.column_stack(channel_values)
    return output


def _read_metadata(h5_file: h5py.File, signal_root: str) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "attrs": _attrs_to_dict(h5_file.attrs),
        "signal_root": signal_root,
    }
    for path in (
        "Configurations/FPConsole/TimeseriesSettings",
        "Configurations/FPConsole",
    ):
        if path in h5_file:
            metadata[path] = _attrs_to_dict(h5_file[path].attrs)
    return metadata


def _attrs_to_dict(attrs: h5py.AttributeManager) -> dict[str, Any]:
    return {key: _to_python(value) for key, value in attrs.items()}


def _to_python(value: Any) -> Any:
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    if isinstance(value, np.generic):
        return _to_python(value.item())
    if isinstance(value, np.ndarray):
        if value.shape == ():
            return _to_python(value.item())
        return [_to_python(item) for item in value.tolist()]
    return value


__all__ = ["DoricFileError", "load_doric"]
