"""Circadian fiber photometry analysis utilities.

Analyses are discoverable from ``circadian_fiber_photometry.analyses``. Doric
HDF5 loading lives in ``circadian_fiber_photometry.io`` and synthetic Doric
generation lives in ``circadian_fiber_photometry.simulation``. Common functions
are also exported at the package root for compatibility.
"""

from .analyses import ANALYSES, get_analysis, list_analyses, run_analysis
from .io import (
    DoricFileError,
    TDTDependencyError,
    TDTExtractEpoc,
    TDTExtractError,
    TDTExtractMetadata,
    TDTExtractStream,
    TDTExtractSummary,
    load_doric,
    write_tdt_extract,
)
from .models import AnalysisResult, AnalysisSpec, DoricDataset
from .phasic import (
    compute_phasic_level,
    compute_phasic_trace,
    count_events,
    extract_light_pulse_windows,
    integrated_fluorescence,
    irls_dynamic_correction,
    percentile_adjust,
    positive_only,
)
from .pipeline import analyze_sessions
from .results import (
    CircadianAnalysisResult,
    DffFitResult,
    EventDetectionResult,
    IntervalHoursEstimate,
    IRLSResult,
    LightPulseWindowResult,
    SessionizedStreamPair,
    TimestampGapReport,
)
from .simulation import (
    SyntheticDoricConfig,
    SyntheticDoricSummary,
    SyntheticGaussianNoiseConfig,
    SyntheticRandomCalciumEventConfig,
    SyntheticScheduledCalciumEventConfig,
    SyntheticSignalConfig,
    SyntheticTDTBatchSummary,
    SyntheticTDTExtractionRecord,
    SyntheticTDTSubject,
    SyntheticTonicComponentConfig,
    SyntheticTTLBehaviorCodeConfig,
    SyntheticTTLBehaviorEventConfig,
    SyntheticTTLBehaviorEventSummary,
    SyntheticTTLRandomBehaviorEventConfig,
    add_gaussian_noise,
    add_random_calcium_events,
    add_scheduled_calcium_events,
    add_tonic_component,
    build_tdt_epocs_from_behavior_events,
    export_synthetic_tdt_extracts,
    generate_synthetic_doric,
)
from .streams import (
    analyze_stream_pair,
    detect_stream_gaps,
    estimate_interval_hours,
    sessionize_stream_pair,
)
from .tonic import (
    compute_average_level,
    compute_raw_median_level,
    compute_tonic_level,
    detrend_levels_by_moving_window,
    fit_405_to_465,
    zscore_levels_by_moving_window,
)

__all__ = [
    "ANALYSES",
    "AnalysisResult",
    "AnalysisSpec",
    "CircadianAnalysisResult",
    "DffFitResult",
    "DoricDataset",
    "DoricFileError",
    "EventDetectionResult",
    "IRLSResult",
    "IntervalHoursEstimate",
    "LightPulseWindowResult",
    "SessionizedStreamPair",
    "SyntheticDoricConfig",
    "SyntheticDoricSummary",
    "SyntheticGaussianNoiseConfig",
    "SyntheticRandomCalciumEventConfig",
    "SyntheticScheduledCalciumEventConfig",
    "SyntheticSignalConfig",
    "SyntheticTDTBatchSummary",
    "SyntheticTDTExtractionRecord",
    "SyntheticTDTSubject",
    "SyntheticTTLBehaviorCodeConfig",
    "SyntheticTTLBehaviorEventConfig",
    "SyntheticTTLBehaviorEventSummary",
    "SyntheticTTLRandomBehaviorEventConfig",
    "SyntheticTonicComponentConfig",
    "TDTDependencyError",
    "TDTExtractEpoc",
    "TDTExtractError",
    "TDTExtractMetadata",
    "TDTExtractStream",
    "TDTExtractSummary",
    "TimestampGapReport",
    "add_gaussian_noise",
    "add_random_calcium_events",
    "add_scheduled_calcium_events",
    "add_tonic_component",
    "analyze_sessions",
    "analyze_stream_pair",
    "build_tdt_epocs_from_behavior_events",
    "compute_average_level",
    "compute_phasic_level",
    "compute_phasic_trace",
    "compute_raw_median_level",
    "compute_tonic_level",
    "count_events",
    "detect_stream_gaps",
    "detrend_levels_by_moving_window",
    "estimate_interval_hours",
    "export_synthetic_tdt_extracts",
    "extract_light_pulse_windows",
    "fit_405_to_465",
    "generate_synthetic_doric",
    "get_analysis",
    "integrated_fluorescence",
    "irls_dynamic_correction",
    "list_analyses",
    "load_doric",
    "percentile_adjust",
    "positive_only",
    "run_analysis",
    "sessionize_stream_pair",
    "write_tdt_extract",
    "zscore_levels_by_moving_window",
]
